### ISSUE TITLE
scrollbar on editview 

### ISSUE THREAD

**Issue by barra** [genius-crm/Template-responsive#4]
form-div contents-bottomscroll has not required scroll bar, check code 

``` css
    contents-bottomscroll {
    overflow-x: auto !important;}
```

on skin style.css
